### ISSUE TITLE
Bluetooth conectivity

### ISSUE THREAD

**Issue by omulverde** [HiranChaudhuri/Webradio_v4#25]
I make a big box for Webradio and I want to be also bluetooth speaker. I think is useful. Otherwise I have to put in box an bluetooth receiver and mix the audio signal with output of Pi to send to amplifier.

**Comment by Acer54** [comment]
webradio-py is just a front-end for "mpd" (Music Player Daemon). If you plan to use bluetooth speakers as an output, this should be possible as long as mpd is able to do this.
A good starting point can be found here: [https://unix.stackexchange.com/questions/517793/mpd-with-bluetooth-speaker-has-no-sound](https://unix.stackexchange.com/questions/517793/mpd-with-bluetooth-speaker-has-no-sound)

**Comment by HiranChaudhuri** [comment]
I second Acer's comment that Webradio is just a UI to control MPD. However I feel omulverde wants to make a box that can play from different sources, like internet radio, local media but also receive music from a mobile phone.

In this case the Raspberry is the bluetooth receiver, not the sender. There is a fine tutorial here that could help: https://www.instructables.com/id/Bluetooth-Speakers-using-Raspberry-Pi/

**Comment by omulverde** [comment]
I will solve the problem with chinese audio mixer. Thanks.
